sudo: false

language: go
go:
- '1.13'
env:
- GO111MODULE=on

services:
- docker

install:
- go get -t
- go get github.com/mattn/goveralls

script:
- go vet
- go test -v -race
- go test -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

branches:
  only:
  - master

matrix:
  fast_finish: true

